#ifndef TYPES_HPP_INCLUDED
#define TYPES_HPP_INCLUDED

enum eCoreType
{
    CORETYPE_ANY,
    CORETYPE_CHAR,
    CORETYPE_UINT, CORETYPE_INT,
    CORETYPE_U8,  CORETYPE_I8,
    CORETYPE_U16, CORETYPE_I16,
    CORETYPE_U32, CORETYPE_I32,
    CORETYPE_U64, CORETYPE_I64,
    CORETYPE_f32,
    CORETYPE_f64,
};

#endif // TYPES_HPP_INCLUDED
